# Generated by Django 4.0.2 on 2022-03-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_imei',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='phone.phoneimei'),
        ),
    ]
