# Generated by Django 4.0.2 on 2022-03-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_phone_phone_imei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone_imei',
            new_name='phone_id',
        ),
    ]
