# Generated by Django 4.0.2 on 2022-03-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'News_Post', 'verbose_name_plural': 'News_Posts'},
        ),
    ]
