# Generated by Django 4.0.2 on 2022-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='card_author',
            field=models.CharField(blank=True, choices=[('admin', 'Admin')], max_length=100, null=True),
        ),
    ]
