# Generated by Django 4.0.2 on 2022-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_post_options_post_card_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='card_author',
        ),
    ]
